#! /usr/bin/env python
import rospy
import cv2
import numpy as np
from sensor_msgs.msg import Image
from std_msgs.msg import Int16()
from cv_bridge import CvBridge


class DetectLane(object):
    def __init__(self):
        self.cvbridge = CvBridge()
        self.cv_msg = None
        self.sub_filtered_img = rospy.Subscriber("filtered_image", Image, self.make_lane, queue_size=1)
        self.pub_lane_img =  rospy.Publisher("lane_image", Image, queue_size=1)
        self.hue_white_l = rospy.get_param("~detect/lane/white/hue_l", 0)
        self.hue_white_h = rospy.get_param("~detect/lane/white/hue_h", 25)
        self.saturation_white_l = rospy.get_param("~detect/lane/white/saturation_l", 0)
        self.saturation_white_h = rospy.get_param("~detect/lane/white/saturation_h", 36)
        self.lightness_white_l = rospy.get_param("~detect/lane/white/lightness_l", 180)
        self.lightness_white_h = rospy.get_param("~detect/lane/white/lightness_h", 255)

    def 