#!/usr/bin/env python
from __future__ import print_function
import rospy
import numpy as np
import cv2
from cv_bridge import CvBridge
from std_msgs.msg import UInt8, Float64
from sensor_msgs.msg import Image, CompressedImage
from hanwhabot_msgs.srv import *

class DetectStartEnd(object):
    """ This is for service server. It will control motor speed
    """
    def __init__(self):
        self.srv_signal = False
        self.cvbridge = CvBridge()
        self.server = rospy.Service("service_name", StartSignal, self.control_signal)
        self.done_work = "I made it!"

    def control_signal(self, req):
        if req.start == False:
            print("I've done my works")
            self.done_work = "I made it!"
            return StartSignalResponse(self.done_work)

    def spin(self):
        rospy.spin()

if __name__ == "__main__":
    rospy.init_node("motor_speed_control_node")
    node = DetectStartEnd()
    node.spin()