#!/usr/bin/env python
from __future__ import print_function
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge
import numpy as np
import cv2

bridge = CvBridge()

def get_realsense_img(img):
    frame = bridge.imgmsg_to_cv2(img, desired_encoding="passthrough")
    depth_array = np.array(frame, dtype=np.float32)
    distance = depth_array[int(depth_array.shape[1]/2 - 10):int(depth_array.shape[1]/2 + 10), int(depth_array.shape[0]/2 - 10): int(depth_array.shape[0]/2 + 10)]
    distance = cv2.mean(distance)
    print("frame shape is %i  %i"%(frame.shape[1], frame.shape[0]))
    print("center value is ", distance)
    
rospy.init_node("get_realsense")
sub = rospy.Subscriber("/camera/depth/image_rect_raw",Image, get_realsense_img, queue_size=5)
rospy.spin()
